name: Build and Release

on:
  push:
    branches:
      - master
steps:
  - name: Build executable
    run: |
      pip install pyinstaller
      pyinstaller clean.py --onefile
  - name: Create release
    uses: actions/create-release@v1
    with:
      tag_name: v1.0.0
      release_name: v1.0.0
      draft: false
      prerelease: false
  - name: Upload executable
    uses: actions/upload-release-asset@v1
    with:
      upload_url: ${{ github.event.release.upload_url }}
      asset_path: dist/clean.exe
      asset_name: clean.exe
      asset_content_type: application/octet-stream
