name: release-please
on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
      - name: Upload clean.py to Release
        if: ${{ steps.release.outputs.release_created }}
        uses: softprops/action-gh-release@v2
        with:
          files: clean.py