name: release-please
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # required to create releases/tags
      pull-requests: write # required to comment on PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple