name: release-please

on:
  push:
    branches: [master]   # use main if that’s your default
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write          # <-- added

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          # token: ${{ secrets.RELEASE_PLEASE_PAT }}   # uncomment if you add a PAT
